### ISSUE TITLE
Set shm-size for Triton in yaml

### ISSUE THREAD

**Issue by swapkh91** [kserve/kserve#1937]
I want to set `shm-size=1g` while running Triton. For local test it works like `docker run --shm-size=1g ...`

Where can I set this in the yaml to deploy on GKE? As this is an argument that has to be passed to `docker run` command.
@yuzisun

**Comment by swapkh91** [comment]
I tried this [solution](https://stackoverflow.com/questions/46085748/define-size-for-dev-shm-on-container-engine/46434614#46434614), but had to change Knative version to 0.26.0 as earlier versions don't allow usage of `emptyDir`. `config-features` has a flag which can be enabled to use `emptyDir` as volume.

But now I'm getting this error in Triton logs and not sure how to solve it:
```
'boost::interprocess::interprocess_exception' what():  Read-only file system
```

yaml
```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "triton-mms"
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
spec:
  predictor:
    volumes:
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: "1024Mi"
    triton:
      ports:
        - containerPort: 9000
          name: h2c
          protocol: TCP
      storageUri: <model repo>
      image: <triton iamge>
      imagePullPolicy: IfNotPresent
      args:
      - --allow-sagemaker=false
      env:
      - name: OMP_NUM_THREADS
        value: "1"
      volumeMounts:
      - mountPath: /dev/shm
        name: dshm
        readOnly: false
      resources:
        limits:
          nvidia.com/gpu: 1
          memory: "5Gi"
        requests:
          nvidia.com/gpu: 1
          memory: "5Gi"
```

**Comment by swapkh91** [comment]
https://github.com/knative/serving/issues/4417#issuecomment-987972384

Works on the Knative side (v0.26).
Need help here, not sure why I'm getting the `'boost::interprocess::interprocess_exception' what():  Read-only file system` 

Describe pod shows
```
Environment:
      OMP_NUM_THREADS:  1
      PORT:             9000
      K_REVISION:       triton-mms-predictor-default-00001
      K_CONFIGURATION:  triton-mms-predictor-default
      K_SERVICE:        triton-mms-predictor-default
    Mounts:
      /dev/shm from dshm (ro)
      /mnt/models from kserve-provision-location (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-svpj5 (ro)
```

@yuzisun @animeshsingh @ellistarn

**Comment by Phelan164** [comment]
@swapkh91 do you have any update for that issue?
I now also got same problem with triton server
```
│ terminate called after throwing an instance of 'boost::interprocess::interprocess_exception'                                                                                                                                             │
│   what():  Read-only file system       
```

**Comment by swapkh91** [comment]
> @swapkh91 do you have any update for that issue? I now also got same problem with triton server
> 
> ```
> │ terminate called after throwing an instance of 'boost::interprocess::interprocess_exception'                                                                                                                                             │
> │   what():  Read-only file system       
> ```

@Phelan164 this issue still exists
Are you trying to increase `shm-size`?

**Comment by Phelan164** [comment]
@swapkh91 yes, I increased `shm-size` to 2GB but still happening
btw, with that model when I run triton server without kserve, It could run when I set `shm-size` 1 GB.
and other trying, I increase Triton python backend setting 
`--backend-config=python,shm-growth-byte-size=1000000000 --backend-config=python,shm-default-byte-size=1000000000`
but not working. The error is Read-only mod so I think that it not caused from lack of shm size.
I do not know the error come from kserve or triton but when try with older triton server 21.03-py3 (currently I use 21.11-py3), it could load that model but other issue is that also could not load all my models (~10 models)

**Comment by Phelan164** [comment]
<img width="1399" alt="Screen Shot 2021-12-29 at 14 38 38" src="https://user-images.githubusercontent.com/2509508/147638418-e6d025d8-a0cf-4494-b557-3ce073612dc3.png">
btw, it is my logging

**Comment by swapkh91** [comment]
> 

@Phelan164 yeah it wont work on kserve as of now, even some issues with normal kubernetes deployment. I raised [this](https://github.com/triton-inference-server/server/issues/3678) issue, yet to be fixed

If you are just using docker, then setting `--backend-config=python,shm-default-byte-size=16777216` (16MB) works for python backend. By default each model on python backend uses the whole 64MB of shared memory, so you need to change it so that other models get some memory, but you have to check how much you need to set the `shm-default-byte-size` as per your model

**Comment by Phelan164** [comment]
@swapkh91 yes, just try to increase that but it not working.
btw, I also deploy into kubernetes but when I run triton server in container I just add setting `--backend-config=python,shm-default-byte-size= 1000000000 ` (1GB)
I tried with old version 21.03-py3  it could load some models but also could not load all my models

**Comment by swapkh91** [comment]
> @swapkh91 yes, just try to increase that but it not working. btw, I also deploy into kubernetes but when I run triton server in container I just add setting `--backend-config=python,shm-default-byte-size= 1000000000 ` (1GB) I tried with old version 21.03-py3 it could load some models but also could not load all my models

@Phelan164 you have to set `shm-default-byte-size` between 0-64MB as the total shm-size is 64MB (which can be increased only through `emptyDir`), `shm-default-byte-size` sets the shm for 1 model. So if you have 4 python models, you can set `shm-default-byte-size=16777216` (16*4)

**Comment by Phelan164** [comment]
@swapkh91 yes, I see. I just want to confirm that there is no problem with lack of shm-default-byte-size for my model. So I tried to load a single model with shm 1GB and I have emptyDir 2GB. But it got same error

**Comment by Phelan164** [comment]
@swapkh91 I found out that. mount volums mode is always readOnly from knative [here](https://github.com/knative/serving/issues/12459#12438).  I also see that, they already have [PR](https://github.com/knative/serving/pull/12458) for updating that.

**Comment by swapkh91** [comment]
> @swapkh91 I found out that. mount volums mode is always readOnly from knative [here](https://github.com/knative/serving/issues/12459#12438). I also see that, they already have [PR](https://github.com/knative/serving/pull/12458) for updating that.

@Phelan164
it is fixed for knative version 0.26.0. I asked the team [here](https://github.com/knative/serving/issues/4417#issuecomment-987815846). But its read-only on Kserve side right now

**Comment by Phelan164** [comment]
@swapkh91 humm, I think it not fixed readOnly mode. You could see src [here](https://github.com/knative/serving/blob/release-0.26/pkg/apis/serving/v1/revision_defaults.go#L147) and you could refer recently discussion [here](https://github.com/knative/serving/issues/12459#12438)

**Comment by skonto** [comment]
Hi [rw access is allowed](https://github.com/knative/serving/pull/11705) for emptydir only at the moment but full rw pvc support is coming. @Phelan164 the code you mention excludes emptydir volumes. So if emptyDir is used you should get write access unless something else is wrong in the given setup (not K8s spec related).
All other volume types will remain in read-only mode unless explicitly defined otherwise. There are thoughts though to allow completely the K8s pod spec using some flag to enable this on demand eg. for advanced users etc.

**Comment by Phelan164** [comment]
@skonto thanks for your info, 
Just want to confirm, my setting for empty now is using memory not disk, is this support write?
```
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: "1Gi"
```

**Comment by Phelan164** [comment]
@swapkh91 did you try older version of kfserving? did it have same problem or just new version?

**Comment by Phelan164** [comment]
@skonto thanks for your info

**Comment by swapkh91** [comment]
> @swapkh91 did you try older version of kfserving? did it have same problem or just new version?

@Phelan164 just the latest version

**Comment by yuzisun** [comment]
> I tried this [solution](https://stackoverflow.com/questions/46085748/define-size-for-dev-shm-on-container-engine/46434614#46434614), but had to change Knative version to 0.26.0 as earlier versions don't allow usage of `emptyDir`. `config-features` has a flag which can be enabled to use `emptyDir` as volume.
> 
> But now I'm getting this error in Triton logs and not sure how to solve it:
> 
> ```
> 'boost::interprocess::interprocess_exception' what():  Read-only file system
> ```
> 
> yaml
> 
> ```
> apiVersion: "serving.kserve.io/v1beta1"
> kind: "InferenceService"
> metadata:
>   name: "triton-mms"
>   annotations:
>     cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
> spec:
>   predictor:
>     volumes:
>     - name: dshm
>       emptyDir:
>         medium: Memory
>         sizeLimit: "1024Mi"
>     triton:
>       ports:
>         - containerPort: 9000
>           name: h2c
>           protocol: TCP
>       storageUri: <model repo>
>       image: <triton iamge>
>       imagePullPolicy: IfNotPresent
>       args:
>       - --allow-sagemaker=false
>       env:
>       - name: OMP_NUM_THREADS
>         value: "1"
>       volumeMounts:
>       - mountPath: /dev/shm
>         name: dshm
>         readOnly: false
>       resources:
>         limits:
>           nvidia.com/gpu: 1
>           memory: "5Gi"
>         requests:
>           nvidia.com/gpu: 1
>           memory: "5Gi"
> ```

We have tested the above yaml which works with `triton 21.09`, `kserve v0.8.0-rc0` and `knative 1.0`, but with `kserve v0.7.0` you get `what():  Read-only file system` error in triton inference server.

in v0.7.0 somehow it overrides volume mount `ReadOnly` true which is not happening in v0.8.0.
```yaml
volumeMounts:
      - mountPath: /dev/shm
        name: dshm
        readOnly: true
```

**Comment by yuzisun** [comment]
0.8 has been released.
